name: Auto-update metadata

on:
  workflow_dispatch:
  schedule:
    # hourly at minute 10
    - cron: 10 * * * *

jobs:
  auto-update-versions:
    name: Auto-update metadata
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name laurit
          git config user.email laurit@users.noreply.github.com

      - run: ./scripts/update-all.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
